FROM ubuntu:24.04

ARG SALTVERSION=3007
ENV DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && \
  apt-get install -y wget gnupg git && \
  wget -O - https://repo.saltproject.io/salt/py3/ubuntu/24.04/amd64/${SALTVERSION}/SALT-PROJECT-GPG-PUBKEY-2023.gpg | apt-key add - && \
  echo "deb http://repo.saltproject.io/salt/py3/ubuntu/24.04/amd64/${SALTVERSION} noble main" | tee /etc/apt/sources.list.d/saltstack.list && \
  apt-get update && \
  apt-get install -y salt-common
