FROM ubuntu:24.04

ARG SALTVERSION=3007
ENV DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && \
  apt-get install -y curl wget gnupg git && \
  curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | tee /usr/share/keyrings/salt-archive-keyring-2023.pgp && \
  echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring-2023.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" | tee /etc/apt/sources.list.d/saltstack.list && \
  apt-get update && \
  apt-get install -y salt-common
